### ISSUE TITLE
Create integration to https://github.com/home-assistant/home-assistant

### ISSUE THREAD

**Issue by fredrike** [molobrakos/tellsticknet#7]
It would be great to use this library together with the interface of home-assistant.

There already exist a telldus-live plugin, but that suffers for the issues with telldus live and by using the tellstick-net directly with a local interface the live issues can be eliminated.

Here are some documentation on how to integrate plugins to home-assistant
 https://home-assistant.io/developers/add_new_platform/

**Comment by molobrakos** [comment]
I agree! (actually I wrote the current Telldus Live component in Home Assistant). 
I just haven't had time to integrate this into Home Assistant. :-/ I am aware of the shortcomings of the current polling based implementation.

Also, Telldus seem to have published Python-versions of the various protocol decocoders here: https://github.com/telldus/tellstick-server/tree/master/rf433/src/rf433, they probably should be used instead of https://github.com/molobrakos/tellsticknet/tree/master/tellsticknet/protocols

Would you like to contribute, then we could discuss in some other channel?

**Comment by fredrike** [comment]
I've created a chatroom in gitter for future discussions: https://gitter.im/tellsticknet/

**Comment by molobrakos** [comment]
Main issues for integrating into HA.
1. Integrate protocol definitions from https://github.com/telldus/tellstick-server/tree/master/rf433/src/rf433
2. Decide / find out how to map local sensor id to server id, we probably need to add a mapping section to `configuration.yaml` that needs to be edited manually
3. Decide / find out how to map a device on LAN to a device from the API (cloud or local). From the API we only get clientId and name, no IP/MAC. We probably need a mapping section in `configuration.yaml `for this as well.

**Comment by molobrakos** [comment]
Moving issue here: https://github.com/molobrakos/tellduslive/issues/8
